kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: example
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend
          image: registry.kthcloud.com/examples/frontend-example
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: example
  labels:
    app.kubernetes.io/name: frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: frontend